name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run this workflow when you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/web

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
